version: '3'

services:
  data-service:
    image: "hang2loose/qwickpot-data-service:1.0"
    container_name: "data-service"
    ports:
      - "9090:9090"
    depends_on:
      - data-service-db

  data-service-db:
    build: ./mysql
    container_name: data-service-db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "qwickpot"
      MYSQL_USER: "luke"
      MYSQL_PASSWORD: "yoda"
    ports:
      - "3306:3306"
