server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qwickpot
    username: luke
    password: yoda
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
