FROM python:slim

WORKDIR /usr/src/app

EXPOSE 8080

RUN pip install python-socketio
RUN pip install eventlet
RUN pip install PyYaml

COPY Server .
COPY ConfigParser.py .

CMD [ "python", "./WebSocketServer.py" ]